### PR TITLE
Fix dev-server-plus for Angular 13

### PR DESCRIPTION
**Pull request by Timebutt**
This PR addresses #307. Looks like a few options were removed in the Angular 13 upgrade that cause the `ng serve` command to fail. Removing the entries from `schema.json` fixes the issue.

### CODE REVIEW

**Comment by samartomar** [comment]
Request to make this update available, in our project we don't have choice to use anything other than Angular 13. and this fix will be savior

**Comment by Timebutt** [comment]
@manfredsteyer with the release of Angular 13 everybody using `ngx-build-plus` will run into a no longer functional `ng serve` or `ng build`, could you have a look at this PR and release a new version of `ngx-build-plus` if all is in order?

**Comment by samartomar** [comment]
@Timebutt  you are awesome, Thank you I am able to work with a suggested workaround. Thank you so much

**Comment by csumudu** [comment]
@manfredsteyer any plan to merge this soon

**Comment by plamenNachevICB** [comment]
We are also waiting for this update so we can merge changes to our production environment

**Comment by manfredsteyer** [comment]
big thanks!

**Pull request merged**
