### PR TITLE
Enable hidden source maps

### PR DESCRIPTION
**Pull request by ryaa**
See https://github.com/manfredsteyer/ngx-build-plus/issues/88

### CODE REVIEW

**Comment by manfredsteyer** [comment]
thx

**Comment by bjornharvold** [comment]
Hi guys! Will this get merged soon?

**Comment by justinappler** [comment]
@manfredsteyer Any chance you could publish a new version to NPM with the latest code?

**Comment by bjornharvold** [comment]
Any progress on this one @manfredsteyer

**Pull request merged**
